version: 1

merge:
  trigger:
    labels: ["MERGE WHEN READY"]
  ignore:
    labels: ["DO NOT MERGE"]
  method: merge
  delete_after_merge: true
  allow_merge_with_no_checks: true
update:
  trigger:
    labels: ["UPDATE ME"]
  ignore:
    labels: ["DO NOT UPDATE"]
